apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-identity-webhook
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-identity-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-identity-webhook
    spec:
      nodeSelector:
        core: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - pod-identity-webhook
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: pod-identity-webhook
      containers:
        - name: pod-identity-webhook
          image: pod-identity-webhook
          imagePullPolicy: Always
          command:
            - /webhook
            - --in-cluster
            - --namespace=kube-system
            - --service-name=pod-identity-webhook
            - --tls-secret=pod-identity-webhook
            - --annotation-prefix=eks.amazonaws.com
            - --token-audience=sts.amazonaws.com
            - --logtostderr
          volumeMounts:
            - name: webhook-certs
              mountPath: /var/run/app/certs
              readOnly: false
      volumes:
        - name: webhook-certs
          emptyDir: {}
